package:
  name: nextflow
  version: 24.10.3
  epoch: 0
  description: A DSL for data-driven computational pipelines.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - busybox
      - coreutils
      - openjdk-21

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - gradle
      - openjdk-21
      - openjdk-21-default-jvm
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-21-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nextflow-io/nextflow.git
      expected-commit: 6183fdf9dbd9114f5ee86d11bc5e69cbd06501a6
      tag: v${{package.version}}

  - runs: |
      export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
      sed -i 's/jar\.enabled = false/jar.enabled = true/' build.gradle
      ./gradlew build -x test --no-daemon
      ./gradlew shadowJar -x test --no-daemon
      BUILD_PACK=1 ./gradlew pack -x test --no-daemon

      # Create the destination directory for the JAR
      mkdir -p ${{targets.destdir}}/usr/lib/nextflow

      # Move the built JAR to /usr/lib/nextflow
      mv "build/releases/nextflow-${{package.version}}-one.jar" ${{targets.destdir}}/usr/lib/nextflow/

subpackages:
  - name: ${{package.name}}-compat
    description: Compatibility package for Nextflow
    pipeline:
      - runs: |
          # Create directory for launcher scripts
          mkdir -p ${{targets.destdir}}/usr/bin

          # Install the Nextflow launcher script
          install -m755 ./nextflow ${{targets.destdir}}/usr/bin/nextflow

          # Create symlink in /usr/local/bin for broader accessibility
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/nextflow "${{targets.subpkgdir}}/usr/local/bin/nextflow"

          # Create framework directory with version-specific symlink
          mkdir -p ${{targets.subpkgdir}}/.nextflow/framework/${{package.version}}
          ln -s "/usr/lib/nextflow/nextflow-${{package.version}}-one.jar" "${{targets.subpkgdir}}/.nextflow/framework/${{package.version}}/"
    test:
      pipeline:
        - name: Check symlink
          runs: stat /usr/local/bin/nextflow

update:
  enabled: true
  github:
    identifier: nextflow-io/nextflow
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - openjdk-21
        - openjdk-21-default-jvm
        - ${{package.name}}-compat
        - curl
    environment:
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk
  pipeline:
    - name: Test version command
      runs: |
        nextflow -version
    - name: Start Nextflow and verify output
      uses: test/daemon-check-output
      with:
        start: |
          env JAVA_HOME=/usr/lib/jvm/java-21-openjdk nextflow run hello
        timeout: 120
        expected_output: |
          N E X T F L O W
          Pulling nextflow-io/hello ...
          executor >  local
          Hello world!
          Hola world!
