package:
  name: op-geth
  version: "1.101411.6 "
  epoch: 0
  description: The go-ethereum command line interface
  copyright:
    - license: LGPL-3.0-or-later
  dependencies:
    runtime:
      - busybox
      - make

environment:
  contents:
    packages:
      - ca-certificates
      - gcc
      - git
      - linux-headers
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 50b3422b9ac682a8fa503c4f409339a9bff69717
      repository: https://github.com/ethereum-optimism/op-geth
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/geth
      ldflags: |
        -X github.com/ethereum-optimism/op-geth/internal/version.gitCommitID=$(git rev-parse HEAD)
        -X github.com/ethereum-optimism/op-geth/internal/version.version=${{package.version}}
        -X github.com/ethereum-optimism/op-geth/internal/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      output: geth

subpackages:
  - name: ${{package.name}}-clef
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/clef
          ldflags: |
            -X github.com/ethereum-optimism/op-geth/internal/version.gitCommitID=$(git rev-parse HEAD)
            -X github.com/ethereum-optimism/op-geth/internal/version.version=${{package.version}}
            -X github.com/ethereum-optimism/op-geth/internal/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          output: clef
    test:
      pipeline:
        - runs: |
            clef --version
            clef --help

  - name: ${{package.name}}-abigen
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/abigen
          output: abigen
          ldflags: |
            -X github.com/ethereum-optimism/op-geth/internal/version.gitCommitID=$(git rev-parse HEAD)
            -X github.com/ethereum-optimism/op-geth/internal/version.version=${{package.version}}
            -X github.com/ethereum-optimism/op-geth/internal/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    test:
      pipeline:
        - runs: |
            abigen --version
            abigen --help

  - name: ${{package.name}}-devp2p
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/devp2p
          ldflags: |
            -X github.com/ethereum-optimism/op-geth/internal/version.gitCommitID=$(git rev-parse HEAD)
            -X github.com/ethereum-optimism/op-geth/internal/version.version=${{package.version}}
            -X github.com/ethereum-optimism/op-geth/internal/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          output: devp2p
    test:
      pipeline:
        - runs: |
            devp2p --version
            devp2p --help

  - name: ${{package.name}}-evm
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/evm
          ldflags: |
            -X github.com/ethereum-optimism/op-geth/internal/version.gitCommitID=$(git rev-parse HEAD)
            -X github.com/ethereum-optimism/op-geth/internal/version.version=${{package.version}}
            -X github.com/ethereum-optimism/op-geth/internal/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          output: evm
    test:
      pipeline:
        - runs: |
            evm --version
            evm --help

  - name: ${{package.name}}-rlpdump
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/rlpdump
          output: rlpdump
    test:
      pipeline:
        - runs: |
            rlpdump --help

test:
  pipeline:
    - name: version and help tests for geth
      runs: |
        geth version
        geth --help

update:
  enabled: true
  github:
    identifier: ethereum-optimism/op-geth
    strip-prefix: v
    tag-filter: v
