package:
  name: pvc-autoresizer
  version: 0.17.1
  epoch: 0
  description: Auto-resize PersistentVolumeClaim objects based on Prometheus metrics
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8f1c575669c5cb57435695324cf5fee3cd7f2f35
      repository: https://github.com/topolvm/pvc-autoresizer
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.36.0
        golang.org/x/oauth2@v0.27.0

  - runs: |
      export CGO_ENABLED=0

  - uses: go/build
    with:
      packages: ./cmd
      output: pvc-autoresizer

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          ln -sf /usr/bin/pvc-autoresizer ${{targets.subpkgdir}}/pvc-autoresizer

test:
  pipeline:
    - name: Help tests for pvc-autoresizer
      runs: |
        pvc-autoresizer --help

update:
  enabled: true
  github:
    identifier: topolvm/pvc-autoresizer
    strip-prefix: v
    tag-filter: v
