package:
  name: spire
  version: 1.11.0
  epoch: 0
  description: The SPIFFE Runtime Environment
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/spiffe/spire.git
      expected-commit: ca35234a30a2aeb2254dec4db6cf09a1fce3c9d7
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: "./cmd/spire-server"
      output: spire-server

  - uses: go/build
    with:
      packages: "./cmd/spire-agent"
      output: spire-agent

subpackages:
  - name: ${{package.name}}-compat
    description: Compatibility package for spire
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/
          ln -sf /usr/bin/spire-server "${{targets.subpkgdir}}"/spire-server
          ln -sf /usr/bin/spire-agent "${{targets.subpkgdir}}"/spire-agent
    test:
      pipeline:
        - name: stat on symlink
          runs: |
            stat /spire-server
            stat /spire-agent

update:
  enabled: true
  github:
    identifier: spiffe/spire
    strip-prefix: v

test:
  pipeline:
    - runs: |
        spire-server --help
        spire-agent --help
